openjij: openjij.model.chimera_model Namespace Reference
openjij.model.chimera_model Namespace Reference
Functions
def make_ChimeraModel (linear, quadratic)
def make_ChimeraModel_from_JSON (obj)
def ChimeraModel (dict linear=None, dict quadratic=None, float offset=0.0, vartype=SPIN, int unit_num_L=None, model=None, bool gpu=False)
Variables
gpu
unit_num_L
coordinate
_chimera_index
_to_index
Function Documentation
ChimeraModel()
def openjij.model.chimera_model.ChimeraModel (dict linear = None, dict quadratic = None, float offset = 0.0, vartype = SPIN, int unit_num_L = None, model = None, bool gpu = False)
generate ChimeraModel object.
This model deal with chimera graph.
ChimeraModel provide methods to verify whether a given interaction graph matches a Chimera graph and to convert it to cxxjij.graph.Chimera.
Args:
    linear (dict): linear biases
    quadratic (dict): quadratic biases
    offset (float): offset
    vartype: vartype ('SPIN' or 'BINARY')
    unit_num_L (int): unit_num_L
    model (BinaryQuadraticModel): if model is not None, the object is initialized by model.
    gpu (bool): if true, this can be used for gpu samplers.
Returns:
    generated ChimeraModel
Examples:
    Example shows how to initialize ChimeraModel.::
        # This interactions satisfy chimera topology.
        >>> Q={(0, 4): -1, (4, 12): -1}
        >>> chimera_model = ChimeraModel(Q, unit_num_L=2)  # make
        >>> chimera_self.validate_chimera()
References openjij.model.chimera_model.make_ChimeraModel(), and openjij.model.chimera_model.make_ChimeraModel_from_JSON().
Referenced by openjij.model.chimera_model.make_ChimeraModel().
make_ChimeraModel()
def openjij.model.chimera_model.make_ChimeraModel (linear, quadratic)
ChimeraModel factory.
Returns:
    generated ChimeraModel class
References openjij.model.chimera_model.ChimeraModel(), and openjij.model.model.make_BinaryQuadraticModel().
Referenced by openjij.model.chimera_model.ChimeraModel(), and openjij.model.chimera_model.make_ChimeraModel_from_JSON().
make_ChimeraModel_from_JSON()
def openjij.model.chimera_model.make_ChimeraModel_from_JSON (obj)
make ChimeraModel from JSON.
Returns:
    corresponding ChimeraModel type
References openjij.model.chimera_model.make_ChimeraModel().
Referenced by openjij.model.chimera_model.ChimeraModel().
Variable Documentation
_chimera_index
openjij.model.chimera_model._chimera_index private
_to_index
openjij.model.chimera_model._to_index private
coordinate
openjij.model.chimera_model.coordinate
gpu
openjij.model.chimera_model.gpu
unit_num_L
openjij.model.chimera_model.unit_num_L