cimod: fmath::local Namespace Reference
fmath::local Namespace Reference
Classes
struct C
union di
struct ExpdVar
struct ExpVar
union fi
struct LogVar
Typedefs
typedef unsigned long long uint64_t
Functions
unsigned int mask (int x)
uint64_t mask64 (int x)
template<class T >
const T * cast_to (const void *p)
template<class T , size_t N>
size_t NumOfArray (const T(&)[N])
template<size_t EXP_N, size_t LOG_N, size_t EXPD_N>
MIE_ALIGN (32) const ExpVar< EXP_N > C< EXP_N
Variables
const size_t EXP_TABLE_SIZE = 10
const size_t EXPD_TABLE_SIZE = 11
const size_t LOG_TABLE_SIZE = 12
LOG_N
Typedef Documentation
uint64_t
typedef unsigned long long fmath::local::uint64_t
Function Documentation
cast_to()
template<class T > const T* fmath::local::cast_to (const void * p) inline
mask()
unsigned int fmath::local::mask (int x) inline
Referenced by fmath::exp(), fmath::exp_pd(), fmath::expd(), fmath::expd_v(), fmath::local::ExpVar< EXP_TABLE_SIZE >::ExpVar(), fmath::PowGenerator::get(), fmath::log(), and fmath::local::LogVar< LOG_TABLE_SIZE >::LogVar().
mask64()
uint64_t fmath::local::mask64 (int x) inline
Referenced by fmath::local::ExpdVar< EXPD_TABLE_SIZE >::ExpdVar().
MIE_ALIGN()
template<size_t EXP_N, size_t LOG_N, size_t EXPD_N> fmath::local::MIE_ALIGN (32) const
Referenced by fmath::exp_pd().
NumOfArray()
template<class T , size_t N> size_t fmath::local::NumOfArray (const T(&)[N])
Variable Documentation
EXP_TABLE_SIZE
const size_t fmath::local::EXP_TABLE_SIZE = 10
EXPD_TABLE_SIZE
const size_t fmath::local::EXPD_TABLE_SIZE = 11
LOG_N
fmath::local::LOG_N
LOG_TABLE_SIZE
const size_t fmath::local::LOG_TABLE_SIZE = 12